### PR TITLE
Day sc2 incidence

### PR DESCRIPTION
**Pull request by trofimovamw**
Added content for incidence hands-on session

### CODE REVIEW

**Comment by hoelzer** [comment]
Hey @trofimovamw in general this looks good but I am afraid you worked on an older `main` state... I am a bit afraid to merge this. Bc when I pull your branch changes I see that many of the other files are outdated... 

What I will do now: I will take your changes, check them, but then directly add them to the `main`. And then I close this PR w/o merging. ok?

**Comment by trofimovamw** [comment]
Sorry! Sure, no problem and thanks :)

**Comment by hoelzer** [comment]
Can you pls doule chekc @trofimovamw  ? 

https://github.com/rki-mf1/2023-SC2-Data-Science/tree/main/day-sc2-incidence

this is now in `main` already

**Comment by hoelzer** [comment]
If this is ok, we can simply close and delete this PR and branch. 

But then, the missing piece is the project description: 

https://github.com/rki-mf1/2023-SC2-Data-Science/blob/main/projects/project04.md

which seems not complete yet (there are "TODO" links still, ... but I saw that you did some changes). 

I suggest, let's first clarify the hands-on stuff and when this is done, please pull the latest changes to `main` and then you can directly finalize the project description as well. thx!

**Pull request closed without merging**
